import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./animate.css";
import Navbar from "./Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WPU - Web Programming Unpas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="min-h-screen font-body">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
